export const ENDPOINT_BASE_URL = 'https://ee548084-499f-43bb-b451-942060a81754-00-1dz8i3zxrf31f.pike.replit.dev';

export const ENDPOINTS = {
    jimpitan: `${ENDPOINT_BASE_URL}/jimpitan`,
    admin: `${ENDPOINT_BASE_URL}/#/admin`,
    rapel: `${ENDPOINT_BASE_URL}/#/rapel`,
    rapelList: `${ENDPOINT_BASE_URL}/#/rapel-list`
}

export const homeList = [
  { nomor: 1, nama: "Hartono" },
  { nomor: 2, nama: "Yuliyanto" },
  { nomor: 3, nama: "Risal" },
  { nomor: 4, nama: "Wahyono" },
  { nomor: 5, nama: "Doni" },
  { nomor: 6, nama: "Iput" },
  { nomor: 7, nama: "-" },
  { nomor: 8, nama: "Hendra" },
  { nomor: 9, nama: "Bambang" },
  { nomor: 10, nama: "Tri Koesnanto" },
  { nomor: 11, nama: "Herma" },
  { nomor: 12, nama: "Sri Parinem, S.Pd" },
  { nomor: 13, nama: "-" },
  { nomor: 14, nama: "-" },
  { nomor: 15, nama: "Eko" },
  { nomor: 16, nama: "Farid" },
  { nomor: 17, nama: "-" },
  { nomor: 18, nama: "Rini" },
  { nomor: 19, nama: "Adi" },
  { nomor: 20, nama: "Pak Roni" },
  { nomor: 21, nama: "Yudha" },
  { nomor: 22, nama: "Ineke" },
  { nomor: 23, nama: "-" },
  { nomor: 24, nama: "-" },
  { nomor: 25, nama: "Nugroho" },
  { nomor: 26, nama: "Agus" },
  { nomor: 27, nama: "-" },
  { nomor: 28, nama: "Ade" },
  { nomor: 29, nama: "-" },
  { nomor: 30, nama: "Wahyu Sutejo" },
  { nomor: 31, nama: "Amri" },
  { nomor: 32, nama: "Dedy" },
  { nomor: 33, nama: "Roni" },
  { nomor: 34, nama: "-" },
  { nomor: 35, nama: "Sinyo/Aang" },
  { nomor: 36, nama: "-" },
  { nomor: 37, nama: "Ulil" },
  { nomor: 38, nama: "Adinda" },
  { nomor: 39, nama: "Boby" },
  { nomor: 40, nama: "Hari" },
  { nomor: 41, nama: "-" },
  { nomor: 42, nama: "-" },
  { nomor: 43, nama: "Topik" },
  { nomor: 44, nama: "Wahyu Pratama" },
  { nomor: 45, nama: "-" },
  { nomor: 46, nama: "-" },
  { nomor: 47, nama: "-" },
  { nomor: 48, nama: "-" },
  { nomor: 49, nama: "Ilham" },
  { nomor: 50, nama: "Hafidz" },
  { nomor: 51, nama: "Koko" },
  { nomor: 52, nama: "Tri/Yudi" },
  { nomor: 53, nama: "Anwar" },
  { nomor: 54, nama: "Okta" },
  { nomor: 55, nama: "-" },
  { nomor: 56, nama: "-" },
  { nomor: 57, nama: "-" },
  { nomor: 58, nama: "-" },
  { nomor: 59, nama: "Pitaloka" },
  { nomor: 60, nama: "Tri" },
  { nomor: 61, nama: "Royhan" },
  { nomor: 62, nama: "Samsino" },
  { nomor: 63, nama: "Kasto" },
  { nomor: 64, nama: "Wahyu Hidayat" },
  { nomor: 65, nama: "Yahya" },
  { nomor: 66, nama: "-" },
  { nomor: 67, nama: "Endra" },
  { nomor: 68, nama: "Ikhwan" },
];

export const userAccount = [
  { username: "menterijimpitan", password: "menterijimpitan", fullname: "Menteri Jimpitan" },
  { username: "ketua", password: "kepalasuku", fullname: "Ketua Paguyuban" },
];

export const months = [
  { value: 1, label: 'Januari' },
  { value: 2, label: 'Februari' },
  { value: 3, label: 'Maret' },
  { value: 4, label: 'April' },
  { value: 5, label: 'Mei' },
  { value: 6, label: 'Juni' },
  { value: 7, label: 'Juli' },
  { value: 8, label: 'Agustus' },
  { value: 9, label: 'September' },
  { value: 10, label: 'Oktober' },
  { value: 11, label: 'November' },
  { value: 12, label: 'Desember' },
];